name: Prepare

on:
  schedule: # scheduled to run at 23.00 on Saturday (UTC), means 6.00 on Monday (WIB)
    - cron: '0 23 * * 6'
  pull_request:
    branches: [main]
  push:
    branches: [main]
    # paths: ['.github/**.yml', 'src/*', 'tests/*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  configs:
    name: Configure
    uses: projek-xyz/actions/.github/workflows/configure.yml@main
    with:
      php-version: 8.2
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  upstream:
    name: Prepare Upstream Database
    runs-on: ubuntu-latest
    needs: configs
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: ${{ github.repository_owner }}
      UPSTREAM_DB_DATABASE: nusantara

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}
          mysql -e 'CREATE DATABASE ${{ env.UPSTREAM_DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ needs.configs.outputs.composer-cache }}
          key: php-8.2-10.x-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-8.2-10.x--composer-

      # - name: Download previous stat
      #   uses: dawidd6/action-download-artifact@v10
      #   with:
      #     branch: main
      #     name: upstream-stats
      #     path: tests
      #     if_no_artifact_found: warn

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Import databases
        env:
          COLUMNS: 120
        run: ./vendor/bin/testbench nusa:import --fresh --ansi

      - name: Store static resources
        uses: actions/upload-artifact@v4
        with:
          retention-days: 14
          name: static-resources
          path: |
            database/nusa.*.sqlite
            resources/static/**
